export const strings = {
  enterMobileNumber: 'Enter Your Mobile Number',
  subtitleMobile:
    "We'll send you a confirmation and tracking updates for your artisan cake.",
  subtitleMobileSecondary: "We'll use this to track your delivery.",
  next: 'NEXT',
  countryCode: '+974',
  whoAreYouDeliveringFrom: 'Who are you delivering from?',
  selectDeliveryPartner: 'Select your delivery partner to proceed',
  back: 'BACK',
  whatIsYourName: "What's your name?",
  nameSubtitle: 'Please enter your full name for the delivery.',
  enterName: 'Enter Name',
  enterOrderNumber: 'Enter your Order Number',
  orderSubtitle: 'Please enter the order number provided by the partner.',
  placeholderOrder: 'Order Number',
  done: 'Done!',
  orderProcessed: 'Order found and processed successfully.',
  company: 'COMPANY',
  customerName: 'CUSTOMER NAME',
  mobileNumber: 'MOBILE NUMBER',
  orderNumber: 'ORDER NUMBER',
  date: 'DATE',
  newEntry: 'New Entry',
  autoRedirect: 'Auto-redirecting in',
  welcomeBack: 'Welcome back,',
  welcomeSub:
    'We recognized your device. Please confirm your identity to proceed.',
  yesThatsMe: "Yes, that's me",
  notMe: 'Not me',
  updateDetails: 'Update Details',
  deliveringFrom: 'DELIVERING FROM',
  submit: 'SUBMIT',
};
